### ISSUE TITLE
Larger images are still visible when not active.

### ISSUE THREAD

**Issue by afuhrtrumpet** [ruyadorno/SimpleSlider#26]
I am trying to use SimpleSlider (Polymer version) with different sized images, with the following CSS:
```
simple-slider {
	width: 100%;
	height: 500px;
	background: #fff;
}
simple-slider img {
	height: 500px;
}
```
And when smaller images are displayed, you can still see larger images in the background. This is because the slider relies on z-index only and doesn't set the other slides' visible properties.

**Comment by ruyadorno** [comment]
A workaround should now be possible using the `onChange` and `onChangeEnd` callback added on [v0.6.0](https://github.com/ruyadorno/SimpleSlider/releases/tag/v0.6.0)

Although it might not be the perfect solution, it allows for fixing the issue if needed - there might be also honest use cases for wanting to have different sized images displayed at the same time.
