### ISSUE TITLE
Always same direction intended?

### ISSUE THREAD

**Issue by antoniobrandao** [ruyadorno/SimpleSlider#29]
Hello, is SimpleSlider intended to slide always in the same direction, or am I doing something wrong? After adding LEFT/RIGHT arrows in my slideshow it looks really strange to always slide from the same direction.

**Comment by ruyadorno** [comment]
Hi @antoniobrandao, yes, this is intended to be a very basic implementation and a direction control is not provided out of the box.

That said, it's still possible to implement it playing with the internal properties. I just added an example showing how to do it, you can find it on `examples/change-sliding-direction-example.html`.

**Comment by antoniobrandao** [comment]
Hey @ruyadorno thanks for the quick reply and perfect example! :+1:

**Comment by ruyadorno** [comment]
np :smile: glad to help!
